import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'pt' | 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.my_tickets': 'Meus Chamados',
    'nav.new_ticket': 'Novo Chamado',
    'nav.all_tickets': 'Todos os Chamados',
    'nav.hotels': 'Hotéis',
    'nav.users': 'Usuários',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    'nav.tickets': 'Chamados',
    'nav.myTickets': 'Meus Chamados',
    'nav.newTicket': 'Novo Chamado',
    
    // Auth
    'auth.login': 'Entrar',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.forgot_password': 'Esqueceu sua senha?',
    'auth.forgotPassword': 'Esqueci a senha',
    'auth.remember_me': 'Lembrar-me',
    'auth.no_account': 'Não tem uma conta?',
    'auth.register': 'Cadastre-se',
    'auth.loggingIn': 'Entrando...',
    'auth.profile': 'Perfil',
    
    // Dashboard
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.total_tickets': 'Total de Chamados',
    'dashboard.in_progress': 'Em Atendimento',
    'dashboard.completed': 'Concluídos',
    'dashboard.total_hotels': 'Total de Hotéis',
    'dashboard.recent_tickets': 'Chamados Recentes',
    'dashboard.new_today': 'novos hoje',
    'dashboard.waiting_parts': 'aguardando peças',
    'dashboard.this_month': 'Este mês',
    'dashboard.active_users': 'usuários ativos',
    'dashboard.overview': 'Visão Geral',
    'dashboard.openTickets': 'Chamados Abertos',
    'dashboard.inProgress': 'Em Atendimento',
    'dashboard.waitingParts': 'Aguardando Peça',
    'dashboard.monthlyCompleted': 'Concluídos no Mês',
    'dashboard.avgTime': 'Tempo Médio',
    'dashboard.activeTickets': 'Chamados Ativos',
    'dashboard.myActiveTickets': 'Meus Ativos',
    
    // Tickets
    'tickets.title': 'Título',
    'tickets.status': 'Status',
    'tickets.priority': 'Prioridade',
    'tickets.hotel': 'Hotel',
    'tickets.room': 'Quarto',
    'tickets.technician': 'Técnico',
    'tickets.created_at': 'Criado em',
    'tickets.updated_at': 'Atualizado em',
    'tickets.actions': 'Ações',
    'tickets.view': 'Visualizar',
    'tickets.edit': 'Editar',
    'tickets.delete': 'Excluir',
    'tickets.new': 'Novo Chamado',
    'tickets.description': 'Descrição',
    'tickets.category': 'Categoria',
    'tickets.images': 'Imagens',
    'tickets.solution': 'Solução',
    'tickets.no_tickets': 'Nenhum chamado encontrado',
    'tickets.search': 'Buscar chamados...',
    'tickets.filter': 'Filtrar',
    'tickets.export': 'Exportar',
    'tickets.export_csv': 'Exportar CSV',
    'tickets.invalid_date': 'Data inválida',
    'ticket.title': 'Título',
    'ticket.status': 'Status',
    'ticket.priority': 'Prioridade',
    'ticket.category': 'Categoria',
    'ticket.room': 'Quarto',
    'ticket.area': 'Área',
    'ticket.description': 'Descrição',
    'ticket.hotel': 'Hotel',
    'ticket.assignedTo': 'Atribuído a',
    'ticket.createdAt': 'Criado em',
    'ticket.attachImages': 'Anexar Imagens',
    'ticket.solution': 'Solução',
    'ticket.close': 'Fechar Chamado',
    'ticket.reopen': 'Reabrir Chamado',
    'ticket.assign': 'Atribuir',
    'ticket.update': 'Atualizar',
    'ticket.create': 'Criar Chamado',
    'ticket.save': 'Salvar',
    'ticket.cancel': 'Cancelar',
    'ticket.statusNew': 'Novo',
    'ticket.statusInProgress': 'Em Atendimento',
    'ticket.statusWaitingParts': 'Aguardando Peças',
    'ticket.statusCompleted': 'Concluído',
    'ticket.statusCancelled': 'Cancelado',
    
    // Settings
    'settings.profile': 'Perfil',
    'settings.theme': 'Tema',
    'settings.language': 'Idioma',
    'settings.security': 'Segurança',
    'settings.name': 'Nome',
    'settings.email': 'E-mail',
    'settings.role': 'Cargo',
    'settings.current_password': 'Senha Atual',
    'settings.new_password': 'Nova Senha',
    'settings.confirm_password': 'Confirmar Senha',
    'settings.change_password': 'Alterar Senha',
    'settings.light': 'Claro',
    'settings.dark': 'Escuro',
    'settings.system': 'Sistema',
    'settings.portuguese': 'Português',
    'settings.english': 'English',
    'settings.french': 'Français',
    'settings.changePassword': 'Alterar Senha',
    'settings.currentPassword': 'Senha Atual',
    'settings.newPassword': 'Nova Senha',
    'settings.confirmPassword': 'Confirmar Senha',
    'settings.updateProfile': 'Atualizar Perfil',
    'settings.general': 'Geral',
    'settings.appearance': 'Aparência',
    'settings.notifications': 'Notificações',
    
    // Status
    'status.new': 'Novo',
    'status.in_progress': 'Em Atendimento',
    'status.waiting_parts': 'Aguardando Peças',
    'status.completed': 'Concluído',
    'status.cancelled': 'Cancelado',
    
    // Priority
    'priority.low': 'Baixa',
    'priority.medium': 'Média',
    'priority.high': 'Alta',
    'priority.urgent': 'Urgente',
    
    // Common
    'common.loading': 'Carregando...',
    'common.unassigned': 'Não atribuído',
    'common.not_found': 'Não encontrado',
    'common.error_loading': 'Erro ao carregar',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.add': 'Adicionar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.close': 'Fechar',
    'common.open': 'Abrir',
    'common.select': 'Selecionar',
    'common.upload': 'Enviar',
    'common.download': 'Baixar',
    'common.remove': 'Remover',
    'common.add_images': 'Adicionar Imagens',
    'common.image': 'Imagem',
    'common.images': 'Imagens',
    'common.room_area': 'Quarto/Área',
    'common.created_on': 'Criado em',
    'common.manage': 'Gerenciar',
    'common.manage_all': 'Gerenciar todos os',
    'common.new_user': 'Novo Usuário',
    'common.new_hotel': 'Novo Hotel',
    'common.date': 'Data',
    'common.start_date': 'Data Inicial',
    'common.end_date': 'Data Final',
    'common.address': 'Endereço',
    'common.contact': 'Contato',
    'common.created': 'Criado em',
    'common.actions': 'Ações',
    'common.profile_info': 'Informações do seu perfil',
    
    // Categories
    'category.electrical': 'Elétrico',
    'category.plumbing': 'Hidráulico',
    'category.air_conditioning': 'Ar Condicionado',
    'category.furniture': 'Móveis',
    'category.cleaning': 'Limpeza',
    'category.other': 'Outros',
    
    // Roles
    'role.admin': 'Administrador',
    'role.technician': 'Técnico',
    'role.reception': 'Recepção',
    
    // Users
    'user.name': 'Nome',
    'user.email': 'Email',
    'user.role': 'Cargo',
    'user.status': 'Status',
    'user.active': 'Ativo',
    'user.inactive': 'Inativo',
    'user.createdAt': 'Criado em',
    'user.actions': 'Ações',
    'user.edit': 'Editar',
    'user.delete': 'Excluir',
    'user.newUser': 'Novo Usuário',
    'user.createUser': 'Criar Usuário',
    'user.updateUser': 'Atualizar Usuário',
    
    // Hotels
    'hotel.name': 'Nome',
    'hotel.address': 'Endereço',
    'hotel.city': 'Cidade',
    'hotel.state': 'Estado',
    'hotel.country': 'País',
    'hotel.phone': 'Telefone',
    'hotel.email': 'Email',
    'hotel.active': 'Ativo',
    'hotel.inactive': 'Inativo',
    'hotel.createdAt': 'Criado em',
    'hotel.actions': 'Ações',
    'hotel.edit': 'Editar',
    'hotel.delete': 'Excluir',
    'hotel.newHotel': 'Novo Hotel',
    'hotel.createHotel': 'Criar Hotel',
    'hotel.updateHotel': 'Atualizar Hotel',
    'hotel.users': 'Usuários',
    'hotel.viewUsers': 'Ver Usuários',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.my_tickets': 'My Tickets',
    'nav.new_ticket': 'New Ticket',
    'nav.all_tickets': 'All Tickets',
    'nav.hotels': 'Hotels',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.tickets': 'Tickets',
    'nav.myTickets': 'My Tickets',
    'nav.newTicket': 'New Ticket',
    
    // Auth
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgot_password': 'Forgot your password?',
    'auth.forgotPassword': 'Forgot password',
    'auth.remember_me': 'Remember me',
    'auth.no_account': "Don't have an account?",
    'auth.register': 'Sign up',
    'auth.loggingIn': 'Logging in...',
    'auth.profile': 'Profile',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.total_tickets': 'Total Tickets',
    'dashboard.in_progress': 'In Progress',
    'dashboard.completed': 'Completed',
    'dashboard.total_hotels': 'Total Hotels',
    'dashboard.recent_tickets': 'Recent Tickets',
    'dashboard.new_today': 'new today',
    'dashboard.waiting_parts': 'waiting parts',
    'dashboard.this_month': 'This month',
    'dashboard.active_users': 'active users',
    'dashboard.overview': 'Overview',
    'dashboard.openTickets': 'Open Tickets',
    'dashboard.inProgress': 'In Progress',
    'dashboard.waitingParts': 'Waiting Parts',
    'dashboard.monthlyCompleted': 'Monthly Completed',
    'dashboard.avgTime': 'Average Time',
    'dashboard.activeTickets': 'Active Tickets',
    'dashboard.myActiveTickets': 'My Active',
    
    // Tickets
    'tickets.title': 'Title',
    'tickets.status': 'Status',
    'tickets.priority': 'Priority',
    'tickets.hotel': 'Hotel',
    'tickets.room': 'Room',
    'tickets.technician': 'Technician',
    'tickets.created_at': 'Created at',
    'tickets.updated_at': 'Updated at',
    'tickets.actions': 'Actions',
    'tickets.view': 'View',
    'tickets.edit': 'Edit',
    'tickets.delete': 'Delete',
    'tickets.new': 'New Ticket',
    'tickets.description': 'Description',
    'tickets.category': 'Category',
    'tickets.images': 'Images',
    'tickets.solution': 'Solution',
    'tickets.no_tickets': 'No tickets found',
    'tickets.search': 'Search tickets...',
    'tickets.filter': 'Filter',
    'tickets.export': 'Export',
    'tickets.export_csv': 'Export CSV',
    'tickets.invalid_date': 'Invalid date',
    'ticket.title': 'Title',
    'ticket.status': 'Status',
    'ticket.priority': 'Priority',
    'ticket.category': 'Category',
    'ticket.room': 'Room',
    'ticket.area': 'Area',
    'ticket.description': 'Description',
    'ticket.hotel': 'Hotel',
    'ticket.assignedTo': 'Assigned to',
    'ticket.createdAt': 'Created at',
    'ticket.attachImages': 'Attach Images',
    'ticket.solution': 'Solution',
    'ticket.close': 'Close Ticket',
    'ticket.reopen': 'Reopen Ticket',
    'ticket.assign': 'Assign',
    'ticket.update': 'Update',
    'ticket.create': 'Create Ticket',
    'ticket.save': 'Save',
    'ticket.cancel': 'Cancel',
    'ticket.statusNew': 'New',
    'ticket.statusInProgress': 'In Progress',
    'ticket.statusWaitingParts': 'Waiting Parts',
    'ticket.statusCompleted': 'Completed',
    'ticket.statusCancelled': 'Cancelled',
    
    // Settings
    'settings.profile': 'Profile',
    'settings.theme': 'Theme',
    'settings.language': 'Language',
    'settings.security': 'Security',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.role': 'Role',
    'settings.current_password': 'Current Password',
    'settings.new_password': 'New Password',
    'settings.confirm_password': 'Confirm Password',
    'settings.change_password': 'Change Password',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.portuguese': 'Portuguese',
    'settings.english': 'English',
    'settings.french': 'French',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.updateProfile': 'Update Profile',
    'settings.general': 'General',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    
    // Status
    'status.new': 'New',
    'status.in_progress': 'In Progress',
    'status.waiting_parts': 'Waiting Parts',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    
    // Priority
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    'priority.urgent': 'Urgent',
    
    // Common
    'common.loading': 'Loading...',
    'common.unassigned': 'Unassigned',
    'common.not_found': 'Not found',
    'common.error_loading': 'Error loading',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.remove': 'Remove',
    'common.add_images': 'Add Images',
    'common.image': 'Image',
    'common.images': 'Images',
    'common.room_area': 'Room/Area',
    'common.created_on': 'Created on',
    'common.manage': 'Manage',
    'common.manage_all': 'Manage all',
    'common.new_user': 'New User',
    'common.new_hotel': 'New Hotel',
    'common.date': 'Date',
    'common.start_date': 'Start Date',
    'common.end_date': 'End Date',
    'common.address': 'Address',
    'common.contact': 'Contact',
    'common.created': 'Created',
    'common.actions': 'Actions',
    'common.profile_info': 'Your profile information',
    
    // Categories
    'category.electrical': 'Electrical',
    'category.plumbing': 'Plumbing',
    'category.air_conditioning': 'Air Conditioning',
    'category.furniture': 'Furniture',
    'category.cleaning': 'Cleaning',
    'category.other': 'Other',
    
    // Roles
    'role.admin': 'Administrator',
    'role.technician': 'Technician',
    'role.reception': 'Reception',
    
    // Users
    'user.name': 'Name',
    'user.email': 'Email',
    'user.role': 'Role',
    'user.status': 'Status',
    'user.active': 'Active',
    'user.inactive': 'Inactive',
    'user.createdAt': 'Created at',
    'user.actions': 'Actions',
    'user.edit': 'Edit',
    'user.delete': 'Delete',
    'user.newUser': 'New User',
    'user.createUser': 'Create User',
    'user.updateUser': 'Update User',
    
    // Hotels
    'hotel.name': 'Name',
    'hotel.address': 'Address',
    'hotel.city': 'City',
    'hotel.state': 'State',
    'hotel.country': 'Country',
    'hotel.phone': 'Phone',
    'hotel.email': 'Email',
    'hotel.active': 'Active',
    'hotel.inactive': 'Inactive',
    'hotel.createdAt': 'Created at',
    'hotel.actions': 'Actions',
    'hotel.edit': 'Edit',
    'hotel.delete': 'Delete',
    'hotel.newHotel': 'New Hotel',
    'hotel.createHotel': 'Create Hotel',
    'hotel.updateHotel': 'Update Hotel',
    'hotel.users': 'Users',
    'hotel.viewUsers': 'View Users',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.my_tickets': 'Mes Appels',
    'nav.new_ticket': 'Nouvel Appel',
    'nav.all_tickets': 'Tous les Appels',
    'nav.hotels': 'Hôtels',
    'nav.users': 'Utilisateurs',
    'nav.settings': 'Configurations',
    'nav.logout': 'Déconnexion',
    'nav.tickets': 'Appels',
    'nav.myTickets': 'Mes Appels',
    'nav.newTicket': 'Nouvel Appel',
    
    // Auth
    'auth.login': 'Se connecter',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.forgotPassword': 'Mot de passe oublié',
    'auth.remember_me': 'Se souvenir de moi',
    'auth.no_account': "Vous n'avez pas de compte ?",
    'auth.register': "S'inscrire",
    'auth.loggingIn': 'Connexion...',
    'auth.profile': 'Profil',
    
    // Dashboard
    'dashboard.welcome': 'Bon retour',
    'dashboard.total_tickets': 'Total des Appels',
    'dashboard.in_progress': 'En Cours',
    'dashboard.completed': 'Terminés',
    'dashboard.total_hotels': 'Total des Hôtels',
    'dashboard.recent_tickets': 'Appels Récents',
    'dashboard.new_today': "nouveaux aujourd'hui",
    'dashboard.waiting_parts': 'en attente de pièces',
    'dashboard.this_month': 'Ce mois-ci',
    'dashboard.active_users': 'utilisateurs actifs',
    'dashboard.overview': 'Vue d\'ensemble',
    'dashboard.openTickets': 'Appels Ouverts',
    'dashboard.inProgress': 'En Cours',
    'dashboard.waitingParts': 'En Attente de Pièces',
    'dashboard.monthlyCompleted': 'Terminés ce Mois',
    'dashboard.avgTime': 'Temps Moyen',
    'dashboard.activeTickets': 'Appels Actifs',
    'dashboard.myActiveTickets': 'Mes Actifs',
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.assignedToYou': 'Attribué à vous',
    'dashboard.allTicketsHotels': 'Tous les Appels de Mes Hôtels',
    
    // Tickets
    'tickets.title': 'Titre',
    'tickets.subtitle': 'Gérer tous les tickets de maintenance',
    'tickets.status': 'Statut',
    'tickets.priority': 'Priorité',
    'tickets.hotel': 'Hôtel',
    'tickets.room': 'Chambre',
    'tickets.technician': 'Technicien',
    'tickets.created_at': 'Créé le',
    'tickets.createdAt': 'Créé le',
    'tickets.updated_at': 'Mis à jour le',
    'tickets.actions': 'Actions',
    'tickets.view': 'Voir',
    'tickets.viewAll': 'Voir tous les appels',
    'tickets.edit': 'Modifier',
    'tickets.delete': 'Supprimer',
    'tickets.new': 'Nouvel Appel',
    'tickets.newTicket': 'Nouvel Appel',
    'tickets.description': 'Description',
    'tickets.category': 'Catégorie',
    'tickets.images': 'Images',
    'tickets.solution': 'Solution',
    'tickets.no_tickets': 'Aucun appel trouvé',
    'tickets.noTickets': 'Aucun appel trouvé',
    'tickets.search': 'Rechercher',
    'tickets.searchPlaceholder': 'Rechercher par titre, chambre...',
    'tickets.filter': 'Filtrer',
    'tickets.filters': 'Filtres',
    'tickets.export': 'Exporter',
    'tickets.exportCSV': 'Exporter CSV',
    'tickets.export_csv': 'Exporter CSV',
    'tickets.invalid_date': 'Date invalide',
    'tickets.assigned': 'Attribué',
    'tickets.dateFrom': 'Date de début',
    'tickets.dateTo': 'Date de fin',
    'tickets.clearDateFilter': 'Effacer le filtre de date',
    'ticket.title': 'Titre',
    'ticket.status': 'Statut',
    'ticket.priority': 'Priorité',
    'ticket.category': 'Catégorie',
    'ticket.room': 'Chambre',
    'ticket.area': 'Zone',
    'ticket.description': 'Description',
    'ticket.hotel': 'Hôtel',
    'ticket.assignedTo': 'Attribué à',
    'ticket.createdAt': 'Créé le',
    'ticket.attachImages': 'Joindre des Images',
    'ticket.solution': 'Solution',
    'ticket.close': 'Fermer l\'Appel',
    'ticket.reopen': 'Rouvrir l\'Appel',
    'ticket.assign': 'Attribuer',
    'ticket.update': 'Mettre à jour',
    'ticket.create': 'Créer un Appel',
    'ticket.save': 'Enregistrer',
    'ticket.cancel': 'Annuler',
    'ticket.statusNew': 'Nouveau',
    'ticket.statusInProgress': 'En Cours',
    'ticket.statusWaitingParts': 'En Attente de Pièces',
    'ticket.statusCompleted': 'Terminé',
    'ticket.statusCancelled': 'Annulé',
    
    // Settings
    'settings.profile': 'Profil',
    'settings.theme': 'Thème',
    'settings.language': 'Langue',
    'settings.security': 'Sécurité',
    'settings.name': 'Nom',
    'settings.email': 'E-mail',
    'settings.role': 'Rôle',
    'settings.current_password': 'Mot de passe actuel',
    'settings.new_password': 'Nouveau mot de passe',
    'settings.confirm_password': 'Confirmer le mot de passe',
    'settings.change_password': 'Changer le mot de passe',
    'settings.light': 'Clair',
    'settings.dark': 'Sombre',
    'settings.system': 'Système',
    'settings.themeLight': 'Clair',
    'settings.themeDark': 'Sombre',
    'settings.themeSystem': 'Système',
    'settings.portuguese': 'Português',
    'settings.english': 'English',
    'settings.french': 'Français',
    'settings.changePassword': 'Changer le Mot de Passe',
    'settings.currentPassword': 'Mot de Passe Actuel',
    'settings.newPassword': 'Nouveau Mot de Passe',
    'settings.confirmPassword': 'Confirmer le Mot de Passe',
    'settings.updateProfile': 'Mettre à Jour le Profil',
    'settings.general': 'Général',
    'settings.appearance': 'Apparence',
    'settings.notifications': 'Notifications',
    
    // Status
    'status.new': 'Nouveau',
    'status.in_progress': 'En Cours',
    'status.waiting_parts': 'En Attente de Pièces',
    'status.completed': 'Terminé',
    'status.cancelled': 'Annulé',
    
    // Priority
    'priority.low': 'Basse',
    'priority.medium': 'Moyenne',
    'priority.high': 'Haute',
    'priority.urgent': 'Urgente',
    
    // Common
    'common.loading': 'Chargement...',
    'common.unassigned': 'Non attribué',
    'common.not_found': 'Non trouvé',
    'common.error_loading': 'Erreur de chargement',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.all': 'Tous',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.close': 'Fermer',
    'common.open': 'Ouvrir',
    'common.select': 'Sélectionner',
    'common.upload': 'Télécharger',
    'common.download': 'Télécharger',
    'common.remove': 'Supprimer',
    'common.add_images': 'Ajouter des Images',
    'common.image': 'Image',
    'common.images': 'Images',
    'common.room_area': 'Chambre/Zone',
    'common.created_on': 'Créé le',
    'common.manage': 'Gérer',
    'common.manage_all': 'Gérer tous les',
    'common.new_user': 'Nouvel Utilisateur',
    'common.new_hotel': 'Nouvel Hôtel',
    'common.date': 'Date',
    'common.start_date': 'Date de Début',
    'common.end_date': 'Date de Fin',
    'common.address': 'Adresse',
    'common.contact': 'Contact',
    'common.created': 'Créé le',
    'common.actions': 'Actions',
    'common.profile_info': 'Informations de votre profil',
    'common.view': 'Voir',
    
    // Categories
    'category.electrical': 'Électrique',
    'category.plumbing': 'Plomberie',
    'category.air_conditioning': 'Climatisation',
    'category.furniture': 'Mobilier',
    'category.cleaning': 'Nettoyage',
    'category.other': 'Autres',
    
    // Roles
    'role.admin': 'Administrateur',
    'role.technician': 'Technicien',
    'role.reception': 'Réception',
    
    // Users
    'user.name': 'Nom',
    'user.email': 'E-mail',
    'user.role': 'Rôle',
    'user.status': 'Statut',
    'user.active': 'Actif',
    'user.inactive': 'Inactif',
    'user.createdAt': 'Créé le',
    'user.actions': 'Actions',
    'user.edit': 'Modifier',
    'user.delete': 'Supprimer',
    'user.newUser': 'Nouvel Utilisateur',
    'user.createUser': 'Créer un Utilisateur',
    'user.updateUser': 'Mettre à Jour l\'Utilisateur',
    'user.profile': 'Profil',
    'user.subtitle': 'Gérer les utilisateurs du système et leurs autorisations',
    'user.searchPlaceholder': 'Rechercher par nom ou e-mail...',
    'user.filterByRole': 'Filtrer par rôle',
    'user.noUsers': 'Aucun utilisateur trouvé',
    'user.editUser': 'Modifier l\'Utilisateur',
    'user.editUserDesc': 'Mettre à jour les informations de l\'utilisateur.',
    'user.newUserDesc': 'Ajouter un nouvel utilisateur au système.',
    'user.setNewPassword': 'Définir un nouveau mot de passe pour',
    'user.minimumCharacters': 'Minimum 6 caractères',
    'user.retypePassword': 'Retaper le mot de passe',
    'user.deactivate': 'Désactiver',
    'user.activate': 'Activer',
    
    // Hotels
    'hotel.name': 'Nom',
    'hotel.address': 'Adresse',
    'hotel.city': 'Ville',
    'hotel.state': 'État',
    'hotel.country': 'Pays',
    'hotel.phone': 'Téléphone',
    'hotel.email': 'E-mail',
    'hotel.active': 'Actif',
    'hotel.inactive': 'Inactif',
    'hotel.createdAt': 'Créé le',
    'hotel.actions': 'Actions',
    'hotel.edit': 'Modifier',
    'hotel.delete': 'Supprimer',
    'hotel.newHotel': 'Nouvel Hôtel',
    'hotel.createHotel': 'Créer un Hôtel',
    'hotel.updateHotel': 'Mettre à Jour l\'Hôtel',
    'hotel.users': 'Utilisateurs',
    'hotel.viewUsers': 'Voir les Utilisateurs',
    'hotel.subtitle': 'Gérer les hôtels enregistrés dans le système',
    'hotel.searchPlaceholder': 'Rechercher par nom, adresse ou CNPJ/SIREN...',
    'hotel.cnpj': 'CNPJ/SIREN',
    'hotel.noHotels': 'Aucun hôtel trouvé',
    'hotel.manageUsers': 'Gérer les utilisateurs',
    'hotel.editHotel': 'Modifier l\'Hôtel',
    'hotel.editHotelDesc': 'Modifier les informations de l\'hôtel.',
    'hotel.newHotelDesc': 'Ajouter un nouvel hôtel au système.',
    
    // Settings additional
    'settings.themeSubtitle': 'Choisir le thème de l\'application',
    'settings.themeLightDesc': 'Thème clair pour une meilleure visibilité pendant la journée',
    'settings.themeDarkDesc': 'Thème sombre pour réduire la fatigue oculaire',
    'settings.themeSystemDesc': 'Suivre les préférences du système d\'exploitation',
    'settings.languageSubtitle': 'Choisir la langue de l\'application',
    'settings.preferredLanguage': 'Langue préférée',
    'settings.passwordSubtitle': 'Mettre à jour votre mot de passe d\'accès',
    
    // Common additions
    'common.updating': 'Mise à jour...',
    
    // Errors
    'errors.loadingData': 'Erreur lors du chargement des données',
    'errors.loadingDataDesc': 'Une erreur s\'est produite lors du chargement des données.',
    'errors.loadingTickets': 'Une erreur s\'est produite lors du chargement des appels.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr'; // Francês como padrão para implantação na França
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translation = translations[language]?.[key as keyof typeof translations['pt']];
    if (translation) return translation;
    
    // Fallback to Portuguese if not found
    const fallback = translations.pt[key as keyof typeof translations['pt']];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
